#!/usr/bin/env fish

if test -e ~/Brewfile
	echo "Updating homebrew bundle"
	brew bundle --file ~/Brewfile
end

if test -d ~/.config/iterm2
	echo "Setting iTerm preference folder"
	defaults write com.googlecode.iterm2 PrefsCustomFolder "~/.config/iterm2"
end

# if command -v vim >/dev/null 2>&1; then
# 	echo "Bootstraping Vim"
# 	vim '+PlugInstall'
# fi

# asdf
asdf plugin add crystal
asdf plugin add elixir
asdf plugin add erlang
asdf plugin add kotlin
asdf plugin add mysql
asdf plugin add nodejs
asdf plugin add postgres
asdf plugin add python
asdf plugin add redis
asdf plugin add ruby
asdf plugin add rust

# fish
## install fisher
curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish

## install fisher plugins
fisher add edc/bass
