#!/bin/sh

if [ -f "$HOME/.Brewfile" ]; then
	echo "Updating homebrew bundle"
	brew bundle --global
fi

if [ -d "$HOME/.iterm2" ]; then
	echo "Setting iTerm preference folder"
	defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
fi

if command -v vim >/dev/null 2>&1; then
	echo "Bootstraping Vim"
	vim '+PlugInstall'
fi
