#!/usr/bin/env fish

if test -e ~/Brewfile
	echo "Updating homebrew bundle"
	brew bundle --file ~/Brewfile
end

if test -d ~/.config/iterm2
	echo "Setting iTerm preference folder"
	defaults write com.googlecode.iterm2 PrefsCustomFolder "~/.config/iterm2"
end

# if command -v vim >/dev/null 2>&1; then
# 	echo "Bootstraping Vim"
# 	vim '+PlugInstall'
# fi
